import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, UserButton, SignInButton } from "@clerk/nextjs";

const inter=Inter ({subsets:["latin"]});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="relative min-h-screen">
            {/* Background Image Layer */}
            <div 
              className="fixed inset-0 bg-repeat z-0"
              style={{ 
                backgroundImage: "url('/chatgpt-background.png')",
                backgroundSize: '120px 120px',
              }}
            ></div>
            
            {/* Content Layer */}
            <div className="relative z-10">
              <main>
                {children}
              </main>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
